// Code generated by smithy-go-codegen DO NOT EDIT.

package bedrock

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/bedrock/schemas"
	"github.com/aws/aws-sdk-go-v2/service/bedrock/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Get the offers associated with the specified model.
func (c *Client) ListFoundationModelAgreementOffers(ctx context.Context, params *ListFoundationModelAgreementOffersInput, optFns ...func(*Options)) (*ListFoundationModelAgreementOffersOutput, error) {
	if params == nil {
		params = &ListFoundationModelAgreementOffersInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "ListFoundationModelAgreementOffers", params, optFns, c.addOperationListFoundationModelAgreementOffersMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*ListFoundationModelAgreementOffersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type ListFoundationModelAgreementOffersInput struct {

	// Model Id of the foundation model.
	//
	// This member is required.
	ModelId *string

	// Type of offer associated with the model.
	OfferType types.OfferType

	noSmithyDocumentSerde
}

func (v *ListFoundationModelAgreementOffersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.ListFoundationModelAgreementOffersRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *ListFoundationModelAgreementOffersInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.ModelId != nil {
		s.WriteString(schemas.ListFoundationModelAgreementOffersRequest_modelId, *v.ModelId)
	}
	if v.OfferType != "" {
		s.WriteString(schemas.ListFoundationModelAgreementOffersRequest_offerType, string(v.OfferType))
	}
}

type ListFoundationModelAgreementOffersOutput struct {

	// Model Id of the foundation model.
	//
	// This member is required.
	ModelId *string

	// List of the offers associated with the specified model.
	//
	// This member is required.
	Offers []types.Offer

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *ListFoundationModelAgreementOffersOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.ListFoundationModelAgreementOffersResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *ListFoundationModelAgreementOffersOutput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.ModelId != nil {
		s.WriteString(schemas.ListFoundationModelAgreementOffersResponse_modelId, *v.ModelId)
	}
	serializeOffers(s, schemas.ListFoundationModelAgreementOffersResponse_offers, v.Offers)
}
func (v *ListFoundationModelAgreementOffersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.ListFoundationModelAgreementOffersResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.ListFoundationModelAgreementOffersResponse_modelId:
			v.ModelId = new(string)
			return d.ReadString(schemas.ListFoundationModelAgreementOffersResponse_modelId, v.ModelId)
		case schemas.ListFoundationModelAgreementOffersResponse_offers:
			return deserializeOffers(d, schemas.ListFoundationModelAgreementOffersResponse_offers, &v.Offers)
		}
		return nil
	})
}
func (c *Client) addOperationListFoundationModelAgreementOffersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.ListFoundationModelAgreementOffers, schemas.ListFoundationModelAgreementOffersRequest, schemas.ListFoundationModelAgreementOffersResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.ListFoundationModelAgreementOffers, schemas.ListFoundationModelAgreementOffersRequest, schemas.ListFoundationModelAgreementOffersResponse), output: &ListFoundationModelAgreementOffersOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpListFoundationModelAgreementOffersValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
