version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - export GOPATH=/go
      - export SDK_CODEBUILD_ROOT=`pwd`
      - make get-deps-verify ci-test-no-generate
  post_build:
    commands:
      - echo Build completed on `date`
