// Code generated by smithy-go-codegen DO NOT EDIT.

package costexplorer

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/costexplorer/schemas"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Requests a Savings Plans recommendation generation. This enables you to
// calculate a fresh set of Savings Plans recommendations that takes your latest
// usage data and current Savings Plans inventory into account. You can refresh
// Savings Plans recommendations up to three times daily for a consolidated billing
// family.
//
// StartSavingsPlansPurchaseRecommendationGeneration has no request syntax because
// no input parameters are needed to support this operation.
func (c *Client) StartSavingsPlansPurchaseRecommendationGeneration(ctx context.Context, params *StartSavingsPlansPurchaseRecommendationGenerationInput, optFns ...func(*Options)) (*StartSavingsPlansPurchaseRecommendationGenerationOutput, error) {
	if params == nil {
		params = &StartSavingsPlansPurchaseRecommendationGenerationInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "StartSavingsPlansPurchaseRecommendationGeneration", params, optFns, c.addOperationStartSavingsPlansPurchaseRecommendationGenerationMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*StartSavingsPlansPurchaseRecommendationGenerationOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type StartSavingsPlansPurchaseRecommendationGenerationInput struct {
	noSmithyDocumentSerde
}

func (v *StartSavingsPlansPurchaseRecommendationGenerationInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.StartSavingsPlansPurchaseRecommendationGenerationRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *StartSavingsPlansPurchaseRecommendationGenerationInput) SerializeMembers(s smithy.ShapeSerializer) {
}

type StartSavingsPlansPurchaseRecommendationGenerationOutput struct {

	// The estimated time for when the recommendation generation will complete.
	EstimatedCompletionTime *string

	// The start time of the recommendation generation.
	GenerationStartedTime *string

	// The ID for this specific recommendation.
	RecommendationId *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *StartSavingsPlansPurchaseRecommendationGenerationOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *StartSavingsPlansPurchaseRecommendationGenerationOutput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.EstimatedCompletionTime != nil {
		s.WriteString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_EstimatedCompletionTime, *v.EstimatedCompletionTime)
	}
	if v.GenerationStartedTime != nil {
		s.WriteString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_GenerationStartedTime, *v.GenerationStartedTime)
	}
	if v.RecommendationId != nil {
		s.WriteString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_RecommendationId, *v.RecommendationId)
	}
}
func (v *StartSavingsPlansPurchaseRecommendationGenerationOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_EstimatedCompletionTime:
			v.EstimatedCompletionTime = new(string)
			return d.ReadString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_EstimatedCompletionTime, v.EstimatedCompletionTime)
		case schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_GenerationStartedTime:
			v.GenerationStartedTime = new(string)
			return d.ReadString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_GenerationStartedTime, v.GenerationStartedTime)
		case schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_RecommendationId:
			v.RecommendationId = new(string)
			return d.ReadString(schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse_RecommendationId, v.RecommendationId)
		}
		return nil
	})
}
func (c *Client) addOperationStartSavingsPlansPurchaseRecommendationGenerationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StartSavingsPlansPurchaseRecommendationGeneration, schemas.StartSavingsPlansPurchaseRecommendationGenerationRequest, schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StartSavingsPlansPurchaseRecommendationGeneration, schemas.StartSavingsPlansPurchaseRecommendationGenerationRequest, schemas.StartSavingsPlansPurchaseRecommendationGenerationResponse), output: &StartSavingsPlansPurchaseRecommendationGenerationOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
