// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/paymentcryptographydata/schemas"
	smithy "github.com/aws/smithy-go"
)

// You do not have sufficient access to perform this action.
type AccessDeniedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *AccessDeniedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *AccessDeniedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *AccessDeniedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "AccessDeniedException"
	}
	return *e.ErrorCodeOverride
}
func (e *AccessDeniedException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (v *AccessDeniedException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.AccessDeniedException, func(s *smithy.Schema) error {
		switch s {
		case schemas.AccessDeniedException_Message:
			v.Message = new(string)
			return d.ReadString(schemas.AccessDeniedException_Message, v.Message)
		}
		return nil
	})
}

// The request processing has failed because of an unknown error, exception, or
// failure.
type InternalServerException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InternalServerException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InternalServerException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InternalServerException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InternalServerException"
	}
	return *e.ErrorCodeOverride
}
func (e *InternalServerException) ErrorFault() smithy.ErrorFault { return smithy.FaultServer }
func (v *InternalServerException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.InternalServerException, func(s *smithy.Schema) error {
		switch s {
		case schemas.InternalServerException_Message:
			v.Message = new(string)
			return d.ReadString(schemas.InternalServerException_Message, v.Message)
		}
		return nil
	})
}

// The request was denied due to an invalid resource error.
type ResourceNotFoundException struct {
	Message *string

	ErrorCodeOverride *string

	ResourceId *string

	noSmithyDocumentSerde
}

func (e *ResourceNotFoundException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ResourceNotFoundException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ResourceNotFoundException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "ResourceNotFoundException"
	}
	return *e.ErrorCodeOverride
}
func (e *ResourceNotFoundException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (v *ResourceNotFoundException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.ResourceNotFoundException, func(s *smithy.Schema) error {
		switch s {
		case schemas.ResourceNotFoundException_ResourceId:
			v.ResourceId = new(string)
			return d.ReadString(schemas.ResourceNotFoundException_ResourceId, v.ResourceId)
		}
		return nil
	})
}

// The request was denied due to request throttling.
type ThrottlingException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *ThrottlingException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ThrottlingException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ThrottlingException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "ThrottlingException"
	}
	return *e.ErrorCodeOverride
}
func (e *ThrottlingException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (v *ThrottlingException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.ThrottlingException, func(s *smithy.Schema) error {
		switch s {
		case schemas.ThrottlingException_Message:
			v.Message = new(string)
			return d.ReadString(schemas.ThrottlingException_Message, v.Message)
		}
		return nil
	})
}

// The request was denied due to an invalid request error.
type ValidationException struct {
	Message *string

	ErrorCodeOverride *string

	FieldList []ValidationExceptionField

	noSmithyDocumentSerde
}

func (e *ValidationException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ValidationException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ValidationException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "ValidationException"
	}
	return *e.ErrorCodeOverride
}
func (e *ValidationException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (v *ValidationException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.ValidationException, func(s *smithy.Schema) error {
		switch s {
		case schemas.ValidationException_fieldList:
			return deserializeValidationExceptionFieldList(d, schemas.ValidationException_fieldList, &v.FieldList)
		case schemas.ValidationException_message:
			v.Message = new(string)
			return d.ReadString(schemas.ValidationException_message, v.Message)
		}
		return nil
	})
}

// This request failed verification.
type VerificationFailedException struct {
	Message *string

	ErrorCodeOverride *string

	Reason VerificationFailedReason

	noSmithyDocumentSerde
}

func (e *VerificationFailedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *VerificationFailedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *VerificationFailedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "VerificationFailedException"
	}
	return *e.ErrorCodeOverride
}
func (e *VerificationFailedException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (v *VerificationFailedException) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.VerificationFailedException, func(s *smithy.Schema) error {
		switch s {
		case schemas.VerificationFailedException_Message:
			v.Message = new(string)
			return d.ReadString(schemas.VerificationFailedException_Message, v.Message)
		case schemas.VerificationFailedException_Reason:
			var ev string
			if err := d.ReadString(schemas.VerificationFailedException_Reason, &ev); err != nil {
				return err
			}
			v.Reason = VerificationFailedReason(ev)
			return nil
		}
		return nil
	})
}
