// Code generated by smithy-go-codegen DO NOT EDIT.

package odb

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/odb/types"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Updates the properties of an Autonomous Database backup.
func (c *Client) UpdateAutonomousDatabaseBackup(ctx context.Context, params *UpdateAutonomousDatabaseBackupInput, optFns ...func(*Options)) (*UpdateAutonomousDatabaseBackupOutput, error) {
	if params == nil {
		params = &UpdateAutonomousDatabaseBackupInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "UpdateAutonomousDatabaseBackup", params, optFns, c.addOperationUpdateAutonomousDatabaseBackupMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*UpdateAutonomousDatabaseBackupOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type UpdateAutonomousDatabaseBackupInput struct {

	// The unique identifier of the Autonomous Database backup to update.
	//
	// This member is required.
	AutonomousDatabaseBackupId *string

	// The retention period, in days, for the Autonomous Database backup.
	RetentionPeriodInDays *int32

	noSmithyDocumentSerde
}

type UpdateAutonomousDatabaseBackupOutput struct {

	// The unique identifier of the Autonomous Database backup that was updated.
	//
	// This member is required.
	AutonomousDatabaseBackupId *string

	// The user-friendly name of the Autonomous Database backup.
	DisplayName *string

	// The current status of the Autonomous Database backup.
	Status types.ResourceStatus

	// Additional information about the current status of the Autonomous Database
	// backup, if applicable.
	StatusReason *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationUpdateAutonomousDatabaseBackupMiddlewares(stack *middleware.Stack, options Options) (err error) {
	err = stack.Serialize.Add(&awsAwsjson10_serializeOpUpdateAutonomousDatabaseBackup{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsAwsjson10_deserializeOpUpdateAutonomousDatabaseBackup{}, middleware.After)
	if err != nil {
		return err
	}

	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpUpdateAutonomousDatabaseBackupValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware(options.Region, "UpdateAutonomousDatabaseBackup", options.EndpointResolver != nil), middleware.Before); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
