// Code generated by smithy-go-codegen DO NOT EDIT.

package bedrockagentcore

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/bedrockagentcore/types"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Delete a payment manager session
//
// Permanently removes a payment session record from the database. This is a hard
// delete operation that removes the session completely.
//
// Deleting a non-existent or already-deleted session returns
// ResourceNotFoundException (404).
//
// Authorization: The caller must own the session (accountId, userId, and
// paymentManagerId must match). If authorization fails, a 403 Forbidden error is
// returned.
//
// Errors:
//
//   - ResourceNotFoundException: The session does not exist or has already been
//     deleted
//   - AccessDeniedException: The caller is not authorized to delete this session
//   - ValidationException: Required fields are missing or invalid
//   - InternalServerException: An unexpected server error occurred
func (c *Client) DeletePaymentSession(ctx context.Context, params *DeletePaymentSessionInput, optFns ...func(*Options)) (*DeletePaymentSessionOutput, error) {
	if params == nil {
		params = &DeletePaymentSessionInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "DeletePaymentSession", params, optFns, c.addOperationDeletePaymentSessionMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*DeletePaymentSessionOutput)
	out.ResultMetadata = metadata
	return out, nil
}

// Request structure for deleting a payment session
//
// All fields are required and must match the session owner's identifiers for
// authorization to succeed.
type DeletePaymentSessionInput struct {

	// The payment manager ARN. Must match the session's paymentManagerArn.
	//
	// This member is required.
	PaymentManagerArn *string

	// The payment session ID to delete.
	//
	// This member is required.
	PaymentSessionId *string

	// The user ID making the delete request. Must match the session's userId.
	UserId *string

	noSmithyDocumentSerde
}

// Response structure for deleting a payment session
//
// Returns the deletion status with HTTP 200 status code on successful deletion.
type DeletePaymentSessionOutput struct {

	// The status of the deletion. Always DELETED for successful hard delete.
	//
	// This member is required.
	Status types.PaymentSessionStatus

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationDeletePaymentSessionMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	err = stack.Serialize.Add(&awsRestjson1_serializeOpDeletePaymentSession{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsRestjson1_deserializeOpDeletePaymentSession{}, middleware.After)
	if err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "DeletePaymentSession"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options, c); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpDeletePaymentSessionValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opDeletePaymentSession(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opDeletePaymentSession(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "DeletePaymentSession",
	}
}
