// Code generated by smithy-go-codegen DO NOT EDIT.

package bedrockagent

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/bedrockagent/schemas"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Deletes an action group in an agent.
func (c *Client) DeleteAgentActionGroup(ctx context.Context, params *DeleteAgentActionGroupInput, optFns ...func(*Options)) (*DeleteAgentActionGroupOutput, error) {
	if params == nil {
		params = &DeleteAgentActionGroupInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "DeleteAgentActionGroup", params, optFns, c.addOperationDeleteAgentActionGroupMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*DeleteAgentActionGroupOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type DeleteAgentActionGroupInput struct {

	// The unique identifier of the action group to delete.
	//
	// This member is required.
	ActionGroupId *string

	// The unique identifier of the agent that the action group belongs to.
	//
	// This member is required.
	AgentId *string

	// The version of the agent that the action group belongs to.
	//
	// This member is required.
	AgentVersion *string

	// By default, this value is false and deletion is stopped if the resource is in
	// use. If you set it to true , the resource will be deleted even if the resource
	// is in use.
	SkipResourceInUseCheck bool

	noSmithyDocumentSerde
}

func (v *DeleteAgentActionGroupInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.DeleteAgentActionGroupRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *DeleteAgentActionGroupInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.ActionGroupId != nil {
		s.WriteString(schemas.DeleteAgentActionGroupRequest_actionGroupId, *v.ActionGroupId)
	}
	if v.AgentId != nil {
		s.WriteString(schemas.DeleteAgentActionGroupRequest_agentId, *v.AgentId)
	}
	if v.AgentVersion != nil {
		s.WriteString(schemas.DeleteAgentActionGroupRequest_agentVersion, *v.AgentVersion)
	}
	if v.SkipResourceInUseCheck != false {
		s.WriteBool(schemas.DeleteAgentActionGroupRequest_skipResourceInUseCheck, v.SkipResourceInUseCheck)
	}
}

type DeleteAgentActionGroupOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *DeleteAgentActionGroupOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.DeleteAgentActionGroupResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *DeleteAgentActionGroupOutput) SerializeMembers(s smithy.ShapeSerializer) {
}
func (v *DeleteAgentActionGroupOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.DeleteAgentActionGroupResponse, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationDeleteAgentActionGroupMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DeleteAgentActionGroup, schemas.DeleteAgentActionGroupRequest, schemas.DeleteAgentActionGroupResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DeleteAgentActionGroup, schemas.DeleteAgentActionGroupRequest, schemas.DeleteAgentActionGroupResponse), output: &DeleteAgentActionGroupOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpDeleteAgentActionGroupValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
