---
name: "🐛 Bug Report"
description: Report a bug
title: "(short issue description)"
labels: [bug, needs-triage]
assignees: []
body:
  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
          required: true
        - label: I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: checkboxes
    id: regression
    attributes:
      label: Regression Issue
      description: What is a regression? If it worked in a previous version but doesn't in the latest version, it's considered a
        regression. In this case, please provide specific version number in the report.
      options:
        - label: Select this option if this issue appears to be a regression.
          required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?

        Please include full errors, uncaught exceptions, stack traces, and relevant logs.
        If service responses are relevant, please include wire logs.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
        For more complex issues provide a repo with the smallest sample that reproduces the bug.

        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
        The code sample should be an SSCCE. See http://sscce.org/ for details. In short, please provide a code sample that we can copy/paste, run and reproduce.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false

  - type: textarea
    id: Go-sdk-version
    attributes:
      label: AWS Go SDK V2 Module Versions Used
      description: |
        Output of `go mod graph` or `go.mod` file listing the `github.com/aws/*` entries.
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Compiler and Version used
      description: output of the `go version` command
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
    validations:
      required: true
