// Code generated by smithy-go-codegen DO NOT EDIT.

package cloudhsmv2

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/cloudhsmv2/schemas"
	"github.com/aws/aws-sdk-go-v2/service/cloudhsmv2/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Modifies attributes for CloudHSM backup.
//
// Cross-account use: No. You cannot perform this operation on an CloudHSM backup
// in a different Amazon Web Services account.
func (c *Client) ModifyBackupAttributes(ctx context.Context, params *ModifyBackupAttributesInput, optFns ...func(*Options)) (*ModifyBackupAttributesOutput, error) {
	if params == nil {
		params = &ModifyBackupAttributesInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "ModifyBackupAttributes", params, optFns, c.addOperationModifyBackupAttributesMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*ModifyBackupAttributesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type ModifyBackupAttributesInput struct {

	// The identifier (ID) of the backup to modify. To find the ID of a backup, use
	// the DescribeBackupsoperation.
	//
	// This member is required.
	BackupId *string

	// Specifies whether the service should exempt a backup from the retention policy
	// for the cluster. True exempts a backup from the retention policy. False means
	// the service applies the backup retention policy defined at the cluster.
	//
	// This member is required.
	NeverExpires *bool

	noSmithyDocumentSerde
}

func (v *ModifyBackupAttributesInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.ModifyBackupAttributesRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *ModifyBackupAttributesInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.BackupId != nil {
		s.WriteString(schemas.ModifyBackupAttributesRequest_BackupId, *v.BackupId)
	}
	if v.NeverExpires != nil {
		s.WriteBool(schemas.ModifyBackupAttributesRequest_NeverExpires, *v.NeverExpires)
	}
}

type ModifyBackupAttributesOutput struct {

	// Contains information about a backup of an CloudHSM cluster. All backup objects
	// contain the BackupId , BackupState , ClusterId , and CreateTimestamp
	// parameters. Backups that were copied into a destination region additionally
	// contain the CopyTimestamp , SourceBackup , SourceCluster , and SourceRegion
	// parameters. A backup that is pending deletion will include the DeleteTimestamp
	// parameter.
	Backup *types.Backup

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *ModifyBackupAttributesOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.ModifyBackupAttributesResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *ModifyBackupAttributesOutput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.Backup != nil {
		s.WriteStruct(schemas.ModifyBackupAttributesResponse_Backup)
		v.Backup.SerializeMembers(s)
		s.CloseStruct()
	}
}
func (v *ModifyBackupAttributesOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.ModifyBackupAttributesResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.ModifyBackupAttributesResponse_Backup:
			v.Backup = &types.Backup{}
			return v.Backup.Deserialize(d)
		}
		return nil
	})
}
func (c *Client) addOperationModifyBackupAttributesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.ModifyBackupAttributes, schemas.ModifyBackupAttributesRequest, schemas.ModifyBackupAttributesResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.ModifyBackupAttributes, schemas.ModifyBackupAttributesRequest, schemas.ModifyBackupAttributesResponse), output: &ModifyBackupAttributesOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpModifyBackupAttributesValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
