// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package iam

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/iam/types"
)

const opListRoleTags = "ListRoleTags"

// ListRoleTagsRequest returns a request value for making API operation for
// AWS Identity and Access Management.
//
// Lists the tags that are attached to the specified role. The returned list
// of tags is sorted by tag key. For more information about tagging, see Tagging
// IAM Identities (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html)
// in the IAM User Guide.
//
//    // Example sending a request using ListRoleTagsRequest.
//    req := client.ListRoleTagsRequest(params)
//    resp, err := req.Send(context.TODO())
//    if err == nil {
//        fmt.Println(resp)
//    }
//
// Please also see https://docs.aws.amazon.com/goto/WebAPI/iam-2010-05-08/ListRoleTags
func (c *Client) ListRoleTagsRequest(input *types.ListRoleTagsInput) ListRoleTagsRequest {
	op := &aws.Operation{
		Name:       opListRoleTags,
		HTTPMethod: "POST",
		HTTPPath:   "/",
	}

	if input == nil {
		input = &types.ListRoleTagsInput{}
	}

	req := c.newRequest(op, input, &types.ListRoleTagsOutput{})
	return ListRoleTagsRequest{Request: req, Input: input, Copy: c.ListRoleTagsRequest}
}

// ListRoleTagsRequest is the request type for the
// ListRoleTags API operation.
type ListRoleTagsRequest struct {
	*aws.Request
	Input *types.ListRoleTagsInput
	Copy  func(*types.ListRoleTagsInput) ListRoleTagsRequest
}

// Send marshals and sends the ListRoleTags API request.
func (r ListRoleTagsRequest) Send(ctx context.Context) (*ListRoleTagsResponse, error) {
	r.Request.SetContext(ctx)
	err := r.Request.Send()
	if err != nil {
		return nil, err
	}

	resp := &ListRoleTagsResponse{
		ListRoleTagsOutput: r.Request.Data.(*types.ListRoleTagsOutput),
		response:           &aws.Response{Request: r.Request},
	}

	return resp, nil
}

// ListRoleTagsResponse is the response type for the
// ListRoleTags API operation.
type ListRoleTagsResponse struct {
	*types.ListRoleTagsOutput

	response *aws.Response
}

// SDKResponseMetdata returns the response metadata for the
// ListRoleTags request.
func (r *ListRoleTagsResponse) SDKResponseMetdata() *aws.Response {
	return r.response
}
