// Code generated by smithy-go-codegen DO NOT EDIT.

package ec2instanceconnect

import (
	"github.com/aws/aws-sdk-go-v2/service/ec2instanceconnect/schemas"
	"github.com/aws/aws-sdk-go-v2/service/ec2instanceconnect/types"
	smithy "github.com/aws/smithy-go"
)

// TypeRegistry is the type registry for this service.
var TypeRegistry = &smithy.TypeRegistry{
	Entries: map[string]*smithy.TypeRegistryEntry{
		"com.amazonaws.ec2instanceconnect#AuthException": {
			Schema: schemas.AuthException,
			New:    func() any { return &types.AuthException{} },
		},
		"com.amazonaws.ec2instanceconnect#EC2InstanceNotFoundException": {
			Schema: schemas.EC2InstanceNotFoundException,
			New:    func() any { return &types.EC2InstanceNotFoundException{} },
		},
		"com.amazonaws.ec2instanceconnect#EC2InstanceStateInvalidException": {
			Schema: schemas.EC2InstanceStateInvalidException,
			New:    func() any { return &types.EC2InstanceStateInvalidException{} },
		},
		"com.amazonaws.ec2instanceconnect#EC2InstanceTypeInvalidException": {
			Schema: schemas.EC2InstanceTypeInvalidException,
			New:    func() any { return &types.EC2InstanceTypeInvalidException{} },
		},
		"com.amazonaws.ec2instanceconnect#EC2InstanceUnavailableException": {
			Schema: schemas.EC2InstanceUnavailableException,
			New:    func() any { return &types.EC2InstanceUnavailableException{} },
		},
		"com.amazonaws.ec2instanceconnect#InvalidArgsException": {
			Schema: schemas.InvalidArgsException,
			New:    func() any { return &types.InvalidArgsException{} },
		},
		"com.amazonaws.ec2instanceconnect#SerialConsoleAccessDisabledException": {
			Schema: schemas.SerialConsoleAccessDisabledException,
			New:    func() any { return &types.SerialConsoleAccessDisabledException{} },
		},
		"com.amazonaws.ec2instanceconnect#SerialConsoleSessionLimitExceededException": {
			Schema: schemas.SerialConsoleSessionLimitExceededException,
			New:    func() any { return &types.SerialConsoleSessionLimitExceededException{} },
		},
		"com.amazonaws.ec2instanceconnect#SerialConsoleSessionUnavailableException": {
			Schema: schemas.SerialConsoleSessionUnavailableException,
			New:    func() any { return &types.SerialConsoleSessionUnavailableException{} },
		},
		"com.amazonaws.ec2instanceconnect#SerialConsoleSessionUnsupportedException": {
			Schema: schemas.SerialConsoleSessionUnsupportedException,
			New:    func() any { return &types.SerialConsoleSessionUnsupportedException{} },
		},
		"com.amazonaws.ec2instanceconnect#ServiceException": {
			Schema: schemas.ServiceException,
			New:    func() any { return &types.ServiceException{} },
		},
		"com.amazonaws.ec2instanceconnect#ThrottlingException": {
			Schema: schemas.ThrottlingException,
			New:    func() any { return &types.ThrottlingException{} },
		},
	},
}
