// Code generated by smithy-go-codegen DO NOT EDIT.

package chimesdkmediapipelines

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines/schemas"
	"github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// A structure that contains the static configurations for a media insights
// pipeline.
func (c *Client) CreateMediaInsightsPipelineConfiguration(ctx context.Context, params *CreateMediaInsightsPipelineConfigurationInput, optFns ...func(*Options)) (*CreateMediaInsightsPipelineConfigurationOutput, error) {
	if params == nil {
		params = &CreateMediaInsightsPipelineConfigurationInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "CreateMediaInsightsPipelineConfiguration", params, optFns, c.addOperationCreateMediaInsightsPipelineConfigurationMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*CreateMediaInsightsPipelineConfigurationOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type CreateMediaInsightsPipelineConfigurationInput struct {

	// The elements in the request, such as a processor for Amazon Transcribe or a
	// sink for a Kinesis Data Stream.
	//
	// This member is required.
	Elements []types.MediaInsightsPipelineConfigurationElement

	// The name of the media insights pipeline configuration.
	//
	// This member is required.
	MediaInsightsPipelineConfigurationName *string

	// The ARN of the role used by the service to access Amazon Web Services
	// resources, including Transcribe and Transcribe Call Analytics , on the caller’s
	// behalf.
	//
	// This member is required.
	ResourceAccessRoleArn *string

	// The unique identifier for the media insights pipeline configuration request.
	ClientRequestToken *string

	// The configuration settings for the real-time alerts in a media insights
	// pipeline configuration.
	RealTimeAlertConfiguration *types.RealTimeAlertConfiguration

	// The tags assigned to the media insights pipeline configuration.
	Tags []types.Tag

	noSmithyDocumentSerde
}

func (v *CreateMediaInsightsPipelineConfigurationInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.CreateMediaInsightsPipelineConfigurationRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *CreateMediaInsightsPipelineConfigurationInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.ClientRequestToken != nil {
		s.WriteString(schemas.CreateMediaInsightsPipelineConfigurationRequest_ClientRequestToken, *v.ClientRequestToken)
	}
	serializeMediaInsightsPipelineConfigurationElements(s, schemas.CreateMediaInsightsPipelineConfigurationRequest_Elements, v.Elements)
	if v.MediaInsightsPipelineConfigurationName != nil {
		s.WriteString(schemas.CreateMediaInsightsPipelineConfigurationRequest_MediaInsightsPipelineConfigurationName, *v.MediaInsightsPipelineConfigurationName)
	}
	if v.RealTimeAlertConfiguration != nil {
		s.WriteStruct(schemas.CreateMediaInsightsPipelineConfigurationRequest_RealTimeAlertConfiguration)
		v.RealTimeAlertConfiguration.SerializeMembers(s)
		s.CloseStruct()
	}
	if v.ResourceAccessRoleArn != nil {
		s.WriteString(schemas.CreateMediaInsightsPipelineConfigurationRequest_ResourceAccessRoleArn, *v.ResourceAccessRoleArn)
	}
	serializeTagList(s, schemas.CreateMediaInsightsPipelineConfigurationRequest_Tags, v.Tags)
}

type CreateMediaInsightsPipelineConfigurationOutput struct {

	// The configuration settings for the media insights pipeline.
	MediaInsightsPipelineConfiguration *types.MediaInsightsPipelineConfiguration

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *CreateMediaInsightsPipelineConfigurationOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.CreateMediaInsightsPipelineConfigurationResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.CreateMediaInsightsPipelineConfigurationResponse_MediaInsightsPipelineConfiguration:
			v.MediaInsightsPipelineConfiguration = &types.MediaInsightsPipelineConfiguration{}
			return v.MediaInsightsPipelineConfiguration.Deserialize(d)
		}
		return nil
	})
}
func (c *Client) addOperationCreateMediaInsightsPipelineConfigurationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.CreateMediaInsightsPipelineConfiguration, schemas.CreateMediaInsightsPipelineConfigurationRequest, schemas.CreateMediaInsightsPipelineConfigurationResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.CreateMediaInsightsPipelineConfiguration, schemas.CreateMediaInsightsPipelineConfigurationRequest, schemas.CreateMediaInsightsPipelineConfigurationResponse), output: &CreateMediaInsightsPipelineConfigurationOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "CreateMediaInsightsPipelineConfiguration"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options, c); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addIdempotencyToken_opCreateMediaInsightsPipelineConfigurationMiddleware(stack, options); err != nil {
		return err
	}
	if err = addOpCreateMediaInsightsPipelineConfigurationValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opCreateMediaInsightsPipelineConfiguration(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

type idempotencyToken_initializeOpCreateMediaInsightsPipelineConfiguration struct {
	tokenProvider IdempotencyTokenProvider
}

func (*idempotencyToken_initializeOpCreateMediaInsightsPipelineConfiguration) ID() string {
	return "OperationIdempotencyTokenAutoFill"
}

func (m *idempotencyToken_initializeOpCreateMediaInsightsPipelineConfiguration) HandleInitialize(ctx context.Context, in middleware.InitializeInput, next middleware.InitializeHandler) (
	out middleware.InitializeOutput, metadata middleware.Metadata, err error,
) {
	if m.tokenProvider == nil {
		return next.HandleInitialize(ctx, in)
	}

	input, ok := in.Parameters.(*CreateMediaInsightsPipelineConfigurationInput)
	if !ok {
		return out, metadata, fmt.Errorf("expected middleware input to be of type *CreateMediaInsightsPipelineConfigurationInput ")
	}

	if input.ClientRequestToken == nil {
		t, err := m.tokenProvider.GetIdempotencyToken()
		if err != nil {
			return out, metadata, err
		}
		input.ClientRequestToken = &t
	}
	return next.HandleInitialize(ctx, in)
}
func addIdempotencyToken_opCreateMediaInsightsPipelineConfigurationMiddleware(stack *middleware.Stack, cfg Options) error {
	return stack.Initialize.Add(&idempotencyToken_initializeOpCreateMediaInsightsPipelineConfiguration{tokenProvider: cfg.IdempotencyTokenProvider}, middleware.Before)
}

func newServiceMetadataMiddleware_opCreateMediaInsightsPipelineConfiguration(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "CreateMediaInsightsPipelineConfiguration",
	}
}
