// Code generated by smithy-go-codegen DO NOT EDIT.

package guardduty

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/guardduty/schemas"
	"github.com/aws/aws-sdk-go-v2/service/guardduty/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Updates the mode of an existing custom detection rule association.
func (c *Client) UpdateCustomDetectionRuleAssociation(ctx context.Context, params *UpdateCustomDetectionRuleAssociationInput, optFns ...func(*Options)) (*UpdateCustomDetectionRuleAssociationOutput, error) {
	if params == nil {
		params = &UpdateCustomDetectionRuleAssociationInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "UpdateCustomDetectionRuleAssociation", params, optFns, c.addOperationUpdateCustomDetectionRuleAssociationMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*UpdateCustomDetectionRuleAssociationOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type UpdateCustomDetectionRuleAssociationInput struct {

	// The unique identifier for the association to update.
	//
	// This member is required.
	AssociationId *string

	// The rule execution mode. Valid values: LIVE | DRY_RUN .
	//
	// This member is required.
	Mode types.AssociationMode

	// The unique identifier for the custom detection rule.
	//
	// This member is required.
	RuleId *string

	noSmithyDocumentSerde
}

func (v *UpdateCustomDetectionRuleAssociationInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.UpdateCustomDetectionRuleAssociationRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *UpdateCustomDetectionRuleAssociationInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.AssociationId != nil {
		s.WriteString(schemas.UpdateCustomDetectionRuleAssociationRequest_AssociationId, *v.AssociationId)
	}
	if v.Mode != "" {
		s.WriteString(schemas.UpdateCustomDetectionRuleAssociationRequest_Mode, string(v.Mode))
	}
	if v.RuleId != nil {
		s.WriteString(schemas.UpdateCustomDetectionRuleAssociationRequest_RuleId, *v.RuleId)
	}
}

type UpdateCustomDetectionRuleAssociationOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *UpdateCustomDetectionRuleAssociationOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.UpdateCustomDetectionRuleAssociationResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *UpdateCustomDetectionRuleAssociationOutput) SerializeMembers(s smithy.ShapeSerializer) {
}
func (v *UpdateCustomDetectionRuleAssociationOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.UpdateCustomDetectionRuleAssociationResponse, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationUpdateCustomDetectionRuleAssociationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.UpdateCustomDetectionRuleAssociation, schemas.UpdateCustomDetectionRuleAssociationRequest, schemas.UpdateCustomDetectionRuleAssociationResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.UpdateCustomDetectionRuleAssociation, schemas.UpdateCustomDetectionRuleAssociationRequest, schemas.UpdateCustomDetectionRuleAssociationResponse), output: &UpdateCustomDetectionRuleAssociationOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpUpdateCustomDetectionRuleAssociationValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
