// Code generated by smithy-go-codegen DO NOT EDIT.

package connect

import (
	"context"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Creates a named alias that points to a specific version of a contact flow
// module.
func (c *Client) CreateContactFlowModuleAlias(ctx context.Context, params *CreateContactFlowModuleAliasInput, optFns ...func(*Options)) (*CreateContactFlowModuleAliasOutput, error) {
	if params == nil {
		params = &CreateContactFlowModuleAliasInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "CreateContactFlowModuleAlias", params, optFns, c.addOperationCreateContactFlowModuleAliasMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*CreateContactFlowModuleAliasOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type CreateContactFlowModuleAliasInput struct {

	// The name of the alias.
	//
	// This member is required.
	AliasName *string

	// The identifier of the flow module.
	//
	// This member is required.
	ContactFlowModuleId *string

	// The version of the flow module.
	//
	// This member is required.
	ContactFlowModuleVersion *int64

	// The identifier of the Connect Customer instance. You can [find the instance ID] in the Amazon
	// Resource Name (ARN) of the instance.
	//
	// [find the instance ID]: https://docs.aws.amazon.com/connect/latest/adminguide/find-instance-arn.html
	//
	// This member is required.
	InstanceId *string

	// The description of the alias.
	Description *string

	noSmithyDocumentSerde
}

type CreateContactFlowModuleAliasOutput struct {

	// The Amazon Resource Name (ARN) of the flow module.
	ContactFlowModuleArn *string

	// The identifier of the alias.
	Id *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationCreateContactFlowModuleAliasMiddlewares(stack *middleware.Stack, options Options) (err error) {
	err = stack.Serialize.Add(&awsRestjson1_serializeOpCreateContactFlowModuleAlias{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsRestjson1_deserializeOpCreateContactFlowModuleAlias{}, middleware.After)
	if err != nil {
		return err
	}

	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpCreateContactFlowModuleAliasValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware(options.Region, "CreateContactFlowModuleAlias", options.EndpointResolver != nil), middleware.Before); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
