// Code generated by smithy-go-codegen DO NOT EDIT.

package connect

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/connect/schemas"
	"github.com/aws/aws-sdk-go-v2/service/connect/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Updates the status of the queue.
func (c *Client) UpdateQueueStatus(ctx context.Context, params *UpdateQueueStatusInput, optFns ...func(*Options)) (*UpdateQueueStatusOutput, error) {
	if params == nil {
		params = &UpdateQueueStatusInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "UpdateQueueStatus", params, optFns, c.addOperationUpdateQueueStatusMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*UpdateQueueStatusOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type UpdateQueueStatusInput struct {

	// The identifier of the Connect Customer instance. You can [find the instance ID] in the Amazon
	// Resource Name (ARN) of the instance.
	//
	// [find the instance ID]: https://docs.aws.amazon.com/connect/latest/adminguide/find-instance-arn.html
	//
	// This member is required.
	InstanceId *string

	// The identifier for the queue.
	//
	// This member is required.
	QueueId *string

	// The status of the queue.
	//
	// This member is required.
	Status types.QueueStatus

	noSmithyDocumentSerde
}

func (v *UpdateQueueStatusInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.UpdateQueueStatusRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *UpdateQueueStatusInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.InstanceId != nil {
		s.WriteString(schemas.UpdateQueueStatusRequest_InstanceId, *v.InstanceId)
	}
	if v.QueueId != nil {
		s.WriteString(schemas.UpdateQueueStatusRequest_QueueId, *v.QueueId)
	}
	if v.Status != "" {
		s.WriteString(schemas.UpdateQueueStatusRequest_Status, string(v.Status))
	}
}

type UpdateQueueStatusOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *UpdateQueueStatusOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(nil)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *UpdateQueueStatusOutput) SerializeMembers(s smithy.ShapeSerializer) {
}
func (v *UpdateQueueStatusOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, nil, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationUpdateQueueStatusMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.UpdateQueueStatus, schemas.UpdateQueueStatusRequest, nil)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.UpdateQueueStatus, schemas.UpdateQueueStatusRequest, nil), output: &UpdateQueueStatusOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpUpdateQueueStatusValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}
