// Code generated by smithy-go-codegen DO NOT EDIT.

package securityhub

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/securityhub/schemas"
	"github.com/aws/aws-sdk-go-v2/service/securityhub/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
)

// Lists and describes insights for the specified insight ARNs.
func (c *Client) GetInsights(ctx context.Context, params *GetInsightsInput, optFns ...func(*Options)) (*GetInsightsOutput, error) {
	if params == nil {
		params = &GetInsightsInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "GetInsights", params, optFns, c.addOperationGetInsightsMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*GetInsightsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type GetInsightsInput struct {

	// The ARNs of the insights to describe. If you don't provide any insight ARNs,
	// then GetInsights returns all of your custom insights. It does not return any
	// managed insights.
	InsightArns []string

	// The maximum number of items to return in the response.
	MaxResults *int32

	// The token that is required for pagination. On your first call to the GetInsights
	// operation, set the value of this parameter to NULL .
	//
	// For subsequent calls to the operation, to continue listing data, set the value
	// of this parameter to the value returned from the previous response.
	NextToken *string

	noSmithyDocumentSerde
}

func (v *GetInsightsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.GetInsightsRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *GetInsightsInput) SerializeMembers(s smithy.ShapeSerializer) {
	serializeArnList(s, schemas.GetInsightsRequest_InsightArns, v.InsightArns)
	if v.MaxResults != nil {
		s.WriteInt32(schemas.GetInsightsRequest_MaxResults, *v.MaxResults)
	}
	if v.NextToken != nil {
		s.WriteString(schemas.GetInsightsRequest_NextToken, *v.NextToken)
	}
}

type GetInsightsOutput struct {

	// The insights returned by the operation.
	//
	// This member is required.
	Insights []types.Insight

	// The pagination token to use to request the next page of results.
	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *GetInsightsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.GetInsightsResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *GetInsightsOutput) SerializeMembers(s smithy.ShapeSerializer) {
	serializeInsightList(s, schemas.GetInsightsResponse_Insights, v.Insights)
	if v.NextToken != nil {
		s.WriteString(schemas.GetInsightsResponse_NextToken, *v.NextToken)
	}
}
func (v *GetInsightsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.GetInsightsResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.GetInsightsResponse_Insights:
			return deserializeInsightList(d, schemas.GetInsightsResponse_Insights, &v.Insights)
		case schemas.GetInsightsResponse_NextToken:
			v.NextToken = new(string)
			return d.ReadString(schemas.GetInsightsResponse_NextToken, v.NextToken)
		}
		return nil
	})
}
func (c *Client) addOperationGetInsightsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.GetInsights, schemas.GetInsightsRequest, schemas.GetInsightsResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.GetInsights, schemas.GetInsightsRequest, schemas.GetInsightsResponse), output: &GetInsightsOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

// GetInsightsPaginatorOptions is the paginator options for GetInsights
type GetInsightsPaginatorOptions struct {
	// The maximum number of items to return in the response.
	Limit int32

	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// GetInsightsPaginator is a paginator for GetInsights
type GetInsightsPaginator struct {
	options   GetInsightsPaginatorOptions
	client    GetInsightsAPIClient
	params    *GetInsightsInput
	nextToken *string
	firstPage bool
}

// NewGetInsightsPaginator returns a new GetInsightsPaginator
func NewGetInsightsPaginator(client GetInsightsAPIClient, params *GetInsightsInput, optFns ...func(*GetInsightsPaginatorOptions)) *GetInsightsPaginator {
	if params == nil {
		params = &GetInsightsInput{}
	}

	options := GetInsightsPaginatorOptions{}
	if params.MaxResults != nil {
		options.Limit = *params.MaxResults
	}

	for _, fn := range optFns {
		fn(&options)
	}

	return &GetInsightsPaginator{
		options:   options,
		client:    client,
		params:    params,
		firstPage: true,
		nextToken: params.NextToken,
	}
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *GetInsightsPaginator) HasMorePages() bool {
	return p.firstPage || (p.nextToken != nil && len(*p.nextToken) != 0)
}

// NextPage retrieves the next GetInsights page.
func (p *GetInsightsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*GetInsightsOutput, error) {
	if !p.HasMorePages() {
		return nil, fmt.Errorf("no more pages available")
	}

	params := *p.params
	params.NextToken = p.nextToken

	var limit *int32
	if p.options.Limit > 0 {
		limit = &p.options.Limit
	}
	params.MaxResults = limit

	optFns = append([]func(*Options){
		addIsPaginatorUserAgent,
	}, optFns...)
	result, err := p.client.GetInsights(ctx, &params, optFns...)
	if err != nil {
		return nil, err
	}
	p.firstPage = false

	prevToken := p.nextToken
	p.nextToken = result.NextToken

	if p.options.StopOnDuplicateToken &&
		prevToken != nil &&
		p.nextToken != nil &&
		*prevToken == *p.nextToken {
		p.nextToken = nil
	}

	return result, nil
}

// GetInsightsAPIClient is a client that implements the GetInsights operation.
type GetInsightsAPIClient interface {
	GetInsights(context.Context, *GetInsightsInput, ...func(*Options)) (*GetInsightsOutput, error)
}

var _ GetInsightsAPIClient = (*Client)(nil)
