// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc10

import (
	"context"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc10/types"
)

func (c *Client) OperationWithNestedStructure(ctx context.Context, params *OperationWithNestedStructureInput, optFns ...func(*Options)) (*OperationWithNestedStructureOutput, error) {
	if params == nil { params = &OperationWithNestedStructureInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OperationWithNestedStructure", params, optFns, c.addOperationOperationWithNestedStructureMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OperationWithNestedStructureOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OperationWithNestedStructureInput struct {
	
	// This member is required.
	TopLevel *types.TopLevel
	
	noSmithyDocumentSerde
}

type OperationWithNestedStructureOutput struct {
	
	// This member is required.
	Dialog *types.Dialog
	
	DialogList []types.Dialog
	
	DialogMap map[string]types.Dialog
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (c *Client) addOperationOperationWithNestedStructureMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addOpOperationWithNestedStructureValidationMiddleware(stack); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}
